[Definition]
actionstart = /usr/local/sbin/ipset-probe-action start
actionstop = /usr/local/sbin/ipset-probe-action stop
actionban = /usr/local/sbin/ipset-probe-action ban <ip>
actionunban = /usr/local/sbin/ipset-probe-action unban <ip>
